# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detalhes.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
#net_54e124
#senha:d42c0f54e124
from PyQt5 import QtCore, QtGui, QtWidgets

class Detalhes(object):
    def setupUi(self, Form, objetos):
        Form.setObjectName("Form")
        Form.resize(699, 406)
        Form.setMinimumSize(QtCore.QSize(699, 406))
        Form.setMaximumSize(QtCore.QSize(699, 406))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/hiring.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.551, y1:1, x2:0.546, y2:0, stop:0 rgba(206, 190, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(24, 39))
        self.label_4.setMaximumSize(QtCore.QSize(62, 16777215))
        self.label_4.setStyleSheet("image: url(:/newPrefix/img/hiring.svg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background-color: rgb(237, 226, 107);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cliente = QtWidgets.QTextEdit(self.frame_3)
        self.cliente.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.cliente.setReadOnly(True)
        self.cliente.setObjectName("cliente")
        self.verticalLayout_5.addWidget(self.cliente)
        self.salario = QtWidgets.QTextEdit(self.frame_3)
        self.salario.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.salario.setReadOnly(True)
        self.salario.setObjectName("salario")
        self.verticalLayout_5.addWidget(self.salario)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.beneficio = QtWidgets.QTextEdit(self.frame_4)
        self.beneficio.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.beneficio.setReadOnly(True)
        self.beneficio.setObjectName("beneficio")
        self.verticalLayout_3.addWidget(self.beneficio)
        self.responsabilidade = QtWidgets.QTextEdit(self.frame_4)
        self.responsabilidade.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.responsabilidade.setReadOnly(True)
        self.responsabilidade.setObjectName("responsabilidade")
        self.verticalLayout_3.addWidget(self.responsabilidade)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.requisito = QtWidgets.QTextEdit(self.frame_5)
        self.requisito.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.requisito.setReadOnly(True)
        self.requisito.setObjectName("requisito")
        self.verticalLayout_4.addWidget(self.requisito)
        self.contato = QtWidgets.QTextEdit(self.frame_5)
        self.contato.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.contato.setReadOnly(True)
        self.contato.setObjectName("contato")
        self.verticalLayout_4.addWidget(self.contato)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.link = QtWidgets.QPlainTextEdit(self.frame_7)
        self.link.setMaximumSize(QtCore.QSize(16777215, 31))
        self.link.setStyleSheet("background-color: rgb(234, 223, 105);")
        self.link.setReadOnly(True)
        self.link.setObjectName("link")
        self.verticalLayout_6.addWidget(self.link)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fechar = QtWidgets.QPushButton(self.frame_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fechar.setIcon(icon1)
        self.fechar.setIconSize(QtCore.QSize(32, 32))
        self.fechar.setObjectName("fechar")
        self.verticalLayout_2.addWidget(self.fechar)
        self.verticalLayout.addWidget(self.frame_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.carregar_janela(Form, objetos)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BUSCA EMPREGO CAMPINAS - GREGÓRIO HONORATO"))
        self.label_3.setText(_translate("Form", "BUSCA EMPREGO - GREGHONO"))
        self.contato.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.fechar.setText(_translate("Form", "Fechar"))

    def carregar_janela(self, Dialog, objetos):
        self.fechar.clicked.connect(Dialog.close)
        self.cliente.setText("Clientes:\n" + objetos[0])
        self.salario.setText("Salario:\n" + objetos[1])
        self.beneficio.setText("Benefício:\n" + objetos[2])
        self.responsabilidade.setText("Responsabilidade:\n" + objetos[3])
        self.requisito.setText("Requisitos:\n" + objetos[4])
        self.contato.setText("Contato:\n" + objetos[5])
        self.link.setPlainText("LINK:"+ objetos[6])

import recursos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Detalhes()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
